// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sut.se.toto.domain;

import org.springframework.beans.factory.annotation.Configurable;
import sut.se.toto.domain.Tset;

privileged aspect Tset_Roo_Configurable {
    
    declare @type: Tset: @Configurable;
    
}
